### ISSUE TITLE
Fiji launcher opens command prompt on windows

### ISSUE THREAD

**Issue by hinerm** [apposed/jaunch#42] opened 2024-04-03 14:58 UTC
Double-clicking the Jaunch Fiji launcher `fiji-windows-x64.exe` opens a tied command prompt:

![image](https://github.com/apposed/jaunch/assets/1123809/79639f32-d296-4e89-baff-9bf0aa752e56)

**Comment by ctrueden** [comment] 2024-04-04 00:00
Duplicate of #24.

**Closed** 2024-04-04 00:00 UTC
Labels: bug
